version: '3.1'

services:
  manim:
    image: eulertour/manim:latest
    volumes:
      - ./:/opt/manim
    environment:
      - PYTHONPATH=/opt/manim
    working_dir: /opt/manim
    entrypoint:
      - python
      - -m
      - manim
    network_mode: "none"
